"""empty message

Revision ID: 58f751f57df5
Revises: 
Create Date: 2024-08-24 18:13:01.752883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f751f57df5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('english_term', sa.String(length=255), nullable=False),
    sa.Column('french_term', sa.String(length=255), nullable=False),
    sa.Column('variant_en', sa.String(length=255), nullable=True),
    sa.Column('variant_fr', sa.String(length=255), nullable=True),
    sa.Column('synonyms_en', sa.String(length=255), nullable=True),
    sa.Column('synonyms_fr', sa.String(length=255), nullable=True),
    sa.Column('definition_en', sa.Text(), nullable=True),
    sa.Column('definition_fr', sa.Text(), nullable=True),
    sa.Column('syntactic_cooccurrence_en', sa.Text(), nullable=True),
    sa.Column('syntactic_cooccurrence_fr', sa.Text(), nullable=True),
    sa.Column('lexical_relations_en', sa.Text(), nullable=True),
    sa.Column('lexical_relations_fr', sa.Text(), nullable=True),
    sa.Column('phraseology_en', sa.Text(), nullable=True),
    sa.Column('phraseology_fr', sa.Text(), nullable=True),
    sa.Column('related_term_en', sa.String(length=255), nullable=True),
    sa.Column('related_term_fr', sa.String(length=255), nullable=True),
    sa.Column('contexts_en', sa.Text(), nullable=True),
    sa.Column('contexts_fr', sa.Text(), nullable=True),
    sa.Column('frequent_expression_en', sa.Text(), nullable=True),
    sa.Column('frequent_expression_fr', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terms')
    # ### end Alembic commands ###
